language: objective-c
osx_image: xcode7.2
before_install:
    - rvm use $RVM_RUBY_VERSION
#    - brew update
install:
#    - brew outdated xctool || brew upgrade xctool
    - bundle install --without=documentation --jobs=3 --retry=3
script:
    - xctool -project Glide.xcodeproj -scheme Glide build test -sdk macosx10.11 GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:
    - slather coverage --input-format profdata --scheme Glide Glide.xcodeproj --coveralls --ignore GlideTests/* --travis --source-directory Glide/
cache:
    directories:
        - vendor/bundle