language: objective-c
osx_image: xcode7.2
before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - sudo easy_install cpp-coveralls
    - brew install tree
script:
    - xctool -project Glide.xcodeproj -scheme Glide build test -sdk macosx10.11 GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
    - tree .
    - coveralls
