language: objective-c
osx_image: xcode7.2
xcode_sdk:
xcode_project: Glide.xcodeproj
xcode_scheme: Glide
before_install:
    - sudo easy_install cpp-coveralls
after_success:
    - coveralls --exclude GlideTests --gcov-options '\-lp'
